version: "3.9"
 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-website-backend
    ports:
      - "8182:8182"
    depends_on:
      - mariadb
    image: bradleneus/simple-website-backend
    networks:
      - my-network
 

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_USERNAME=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=maintenance
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
 
volumes:
  db: